<?php

namespace Imc\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;
use Imc\Entity\Candidato;

/**
 * CandidatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatoRepository extends AbstractEntityRepository
{
    public function loginCandidatoPorCpf($cpf, $password)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('u')
            ->from(Candidato::class, 'u')
            ->where($qb->expr()->andX(
                $qb->expr()->eq('u.active', ':active'),
                $qb->expr()->eq('u.cpf', ':cpf'),
                $qb->expr()->eq('u.password', ':password')
            ))
            ->setParameters(['active' => 1, 'cpf' => $cpf, 'password' => $password]);
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }
}
