FROM phpearth/php:7.2-apache

RUN apk add --no-cache composer git openssh \
    # php7.2-apcu \
    # php7.2-dba \
    # php7.2-doc \
    # php7.2-embed \
    # php7.2-enchant \
    php7.2-gd \
    # php7.2-gettext \
    # php7.2-gmp \
    php7.2-imagick \
    # php7.2-imap \
    php7.2-intl \
    # php7.2-ldap \
    # php7.2-mcrypt \
    # php7.2-memcached \
    # php7.2-mongodb \
    # php7.2-mysqlnd \
    # php7.2-odbc \
    php7.2-pdo \
    # php7.2-pdo_odbc \
    php7.2-pdo_mysql \
    php7.2-pdo_pgsql \
    php7.2-pdo_sqlite \
    # php7.2-pgsql \
    # php7.2-phpdbg \
    php7.2-phpunit \
    # php7.2-pickle \
    # php7.2-pspell \
    # php7.2-recode \
    # php7.2-redis \
    # php7.2-snmp \
    # php7.2-soap \
    # php7.2-sodium \
    # php7.2-sqlite3 \
    # php7.2-swoole \
    php7.2-tidy \
    # php7.2-wddx \
    php7.2-xdebug \
    # php7.2-xmlrpc \
    # php7.2-xsl \
    # php7.2-yaml \
    && composer global require hirak/prestissimo;