version: '3'
services:

  db:
    container_name: im-quasar-db
    image: mysql:5.7
    volumes:
      - "./quasar/database/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mvinicius
      MYSQL_DATABASE: mvinicius
      MYSQL_USER: root
      MYSQL_PASSWORD: mvinicius
    ports:
      - "3306:3306"

  api:
    container_name: im-quasar-api
    build: docker/php
    volumes:
      - ./quasar/api/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    restart: always
    environment:
      APP_ENV: 'dev'
    depends_on:
      - db
    working_dir: /var/www/html

volumes:
    database:
    api:
