version: '3'
services:

  db:
    container_name: mv-quasar-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./quasar/database/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mvinicius
      MYSQL_DATABASE: mvinicius
      MYSQL_USER: root
      MYSQL_PASSWORD: mvinicius

  api:
    container_name: mv-quasar-api
    build: docker/php
    ports:
      - 8000:80
    volumes:
      - ./quasar/server/:/var/www/quasar/
      - ./docker/php/php.ini:/etc/php/7.2/php.ini
      - ./docker/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./docker/apache/conf.d/quasar.conf:/etc/apache2/conf.d/quasar.conf
    depends_on:
      - db
    links: 
      - db
    working_dir: /var/www/quasar
    restart: always
    environment:
      APP_ENV: 'dev'
  
  # ng:
  #   container_name: mv-quasar-ng
  #   image: johnpapa/angular-cli
  #   build: docker/angular-cli
  #   ports:
  #     - 8001:4200
  #   links: 
  #     - api
  #   volumes:
  #     - ./quasar/client/:/home/node/app
  #   working_dir: /home/node/app
  #   environment:
  #     NODE_ENV: production
  #   command: ["yarn", "start"]

volumes:
    database:
    server:
    # client:
