<?php

namespace Log\Model\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;

/**
 * LoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoggerRepository extends AbstractEntityRepository
{

}
