<?php

namespace User\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractEntityRepository implements UserRepositoryInterface
{
    public function getNames()
    {
        return $this->createQueryBuilder('u')
        ->select(['u'])
        ->join('u.fkPerfil', 'p', Join::WITH, 'u.fkPerfil = p.id')
        ->groupBy('p.name')
        ->orderBy('p.name', 'ASC')
        ->getQuery()
        ->getResult();
    }

  /**
   * @param string $credential
   * @param string $password
   * @return bool
   */
    public function checkAuthenticationData($credential, $password)
    {
        /** @var \User\Entity\User $user */
        $user = $this->findOneBy(['credential' => $credential]);

        if ($user) {
            if (password_verify($password, $user->getPassword())) {
                return true;
            }
        }
        return false;
    }
}
