<?php

namespace User\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends AbstractEntityRepository
{
    public function getNames()
    {
        return $this->createQueryBuilder('r')
            ->select(['r'])
            ->groupBy('r.name')
            ->orderBy('r.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function getNamesForSelect()
    {
        return $this->createQueryBuilder('r')
            ->select(['r'])
            ->groupBy('r.name')
            ->orderBy('r.name', 'ASC')
            ->distinct()
            ->getQuery()
            ->getResult();
    }
}
