<?php

namespace Midia\Model\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;

/**
 * AudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRepository extends AbstractEntityRepository
{
}
