<?php

namespace Midia\Model\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends AbstractEntityRepository
{
}
