<?php

namespace Log\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * LoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoggerRepository extends AbstractEntityRepository
{

}
