<?php

namespace Imc\Repository;

use Core\Doctrine\ORM\AbstractEntityRepository;

/**
 * ConcursoArquivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcursoArquivoRepository extends AbstractEntityRepository
{
}
